learning_user/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns =[
    path('',views.index,name='index'),
    path('register/',views.register, name='register'),
    path('user_login/',views.user_login,name = 'user_login'),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
    path('userinfo',views.your_profile,name='userprofile')
]

learning_user/learning_user/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('basic_app.urls')),
    path('admin/', admin.site.urls),
]

learning_user/basic_app/models.py
from distutils.command.upload import upload
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User ,on_delete=models.CASCADE)

    #additional classes

    portfolio_site = models.URLField(blank=True)


    profile_pic = models.ImageField(upload_to = 'profile_pics',blank = True)

    def __str__(self):
        return self.user.username

learning_user/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta(): 
        model = User
        fields = ('username','email','password')
    

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')
        

learning_user/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm
from basic_app.models import UserProfileInfo
# for login
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def special(request):
    return HttpResponse('you are loged in , Nice!!')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('basic_app:index'))

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password) # this will hash the password 
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
                
            profile.save() 

            registered = True
            
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'basic_app/registration.html',
        {'user_form':user_form,
        'profile_form':profile_form,
        'registered':registered})

def your_profile(request):
    user_list = UserProfileInfo.objects.order_by('user')
    user_dict = {'user': user_list}
    return render(request,'basic_app/your_prof.html',context=user_dict)

def user_login(request):
    
    if request.method == "POST":   
        username = request.POST.get('username')# it will get username from (name= 'username' )html form we created in login file
        password = request.POST.get('password')
        
        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user) # this is user is return by authenticate
                return HttpResponseRedirect(reverse('basic_app:index')) # if user is login succesfully and active than he will be redirect to index page

            else:
                return HttpResponse("Accout not active")
        else:
            print("some tried to login and failed!")
            print("Username : {} and password {} ".format(username,password))
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request, 'basic_app/login.html',{})

learning_user/templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base file </title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'basic_app/basic.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'basic_app:index' %}">DJANGO</a>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li><a class="nav-link " href="{% url 'basic_app:register' %}">Registration Page</a></li>
              <li><a class="nav-link " href="{% url 'admin:index' %}">Admin Page</a></li>
              <li><a class="nav-link" href="{% url 'basic_app:userprofile' %}">User Profile</a></li>
              {% if user.is_authenticated %}
              <li><a class="nav-link" href="{% url 'basic_app:logout' %}">Logout</a></li>
              {% else %}
              <li><a class='nav-link' href="{% url 'basic_app:user_login' %}">Login</a></li>
              {% endif %}
        </div>
      </nav>
    <div class="container-fluid">
    {% block body_block %}
    {% endblock %}
    </div>
</body>
</html>

learning_user/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="row">
    <div class=" text-black p-5 mt-4 adding">
      <div class="adding2">
      <h1>Dajngo Level Five</h1>
   </div>
    </div>
  </div>
{% endblock %}

learning_user/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

<div class="row">
  <div class=" text-black p-5 mt-4 adding">
    <div class="adding2">
    <h1>Please Login</h1>
    <form action="{% url 'basic_app:user_login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Enter username ">
      <label for="password">Password</label>
      <input type="password" name="password" >
      <input type="submit" name="" value="Login">
    </form>
 </div>
  </div>
</div>

{% endblock %} 

learning_user/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load static %}
{% block body_block %}

<div class ='container-fluid'>    
    <div class="row">
      <div class=" text-black p-5 mt-4 adding">
        <div class="adding2">
          {% if registered %}
              <h1>Thank you for registering!!</h1>
          {% else %}
              <h1>Register here!!</h1>
              <h3>Fill out the form:</h3>
          
              <form  method="post" enctype="multipart/form-data"> <!-- enctype must be incuded when receiving any media form users-->
              {%  csrf_token %}
              {{ user_form.as_p }}
              {{ profile_form.as_p }}
              <input type="submit" name="" value="Register" >
              </form> 
          {% endif %}
       </div>
     </div>
   </div>      
</div>

{% endblock %}

learning_user/templates/basic_app/your_prof.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

      <h1>Here is your details</h1>
      <div>
        {% if user %}
        <ol>
            {% for person in user %}
            <li>User Info</li>
            <ul>
                <li>{{ person.username }}</li>
                <li>{{ person.profile_pic }}</li>
                <li>{{ person.portfolio_site }}</li>
            </ul>
        </ol>
            {% endfor %}
        {% else %}
        <p>NO DATA AVAILABLE</p>
        {% endif %}
        

      </div>

{% endblock %}